# 각 클라이언트가 공통으로 사용하는 구성 정보를 구성 저장소로 이동하자
## 액추에이터 엔드포인트, 유레카, rabbitMq, 카프카 접속정보 등
app:
  eureka-username: u
  eureka-password: '{cipher}bf298f6d5f878b342f9e44bec08cb9ac00b4ce57e98316f030194a225fac89fb'
  eureka-server: localhost
  auth-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/" # 유레카 서버를 가리킴.
    initialInstanceInfoReplicationIntervalSeconds: 5 # 아래의 매캐변수는 시작 시간과 중단된 아미크로 서비스의 인스턴스의 등록 해제에 걸리는 시간 최소화하기 위함
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: '{cipher}17fcf0ae5b8c5cf87de6875b699be4a1746dd493a99d926c7a26a68c422117ef'

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

## 이러한 구성 설정은 개발 단계에선 유용, 상용 시 과도한 정보 제공은 보안상 문제 있음
##  따라서 actuator 엔트포인트 공개 정보는 최소화 필요
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.profiles: docker

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

app:
  eureka-server: eureka
  auth-server: auth-server
