server.port: 8888

spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo # 구성 저장소의 위치를 지정

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

---
spring.profiles: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo

