server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup # 소비자 그룹 생성_products 인스턴스 중 한 인스턴스로만 product 토픽 게시(중복방지)

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3 # 데드 레터 대기열로 이동하기 전에 3회 재시도
  backOffInitialInterval: 500 # 처음 시도 시 500ms
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer: # 데드레터 대기열
  autoBindDlq: true
  republishToDlq: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    com.gongdel: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring.profiles: docker

server.port: 8080

spring.data.mongodb:
  host: mongodb.mongodb
  port: 27017
  database: product-db

spring.rabbitmq:
  host: rabbitmq-headless.rabbitmq
  port: 5672
  username: guest
  password: guest