
server:
  port: 8761
  
# 독립형 유레카 서버의 표준 구선
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    retchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0 # 유레카 서버의 시작 시간을 최소하기 위한 매개변수 1
      response-cache-update-interval-ms: 5000 # 유레카 서버의 시작 시간을 최소하기 위한 매개변수 2